spring:
  application:
    name: redis-passwordless
  data:
    redis:
      host: ${AZURE_CACHE_REDIS_HOST}
      port: 6380
      ssl:
        enabled: true
      azure:
        passwordless-enabled: true
        credential:
          client-id: ${AZURE_CACHE_REDIS_CLIENT_ID}
